version: 2
updates:
- package-ecosystem: nuget
  directory: "/MarketingNotifications.Web.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.IdentityModel.Tokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: System.IdentityModel.Tokens.Jwt
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.Logging
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.JsonWebTokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.0
  - dependency-name: JWT
    versions:
    - 7.3.1
    - 8.0.0
    - 8.1.0
    - 8.1.2
    - 8.1.3
    - 8.1.4
    - 8.1.5
    - 8.1.6
  - dependency-name: Twilio
    versions:
    - 5.53.1
    - 5.54.0
    - 5.56.0
    - 5.57.0
    - 5.58.0
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Portable.BouncyCastle
    versions:
    - 1.8.9
  - dependency-name: RestSharp
    versions:
    - 106.11.7
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
  - dependency-name: Microsoft.AspNet.Mvc
    versions:
    - 5.2.7
- package-ecosystem: nuget
  directory: "/MarketingNotifications.Web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.IdentityModel.Tokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: System.IdentityModel.Tokens.Jwt
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.JsonWebTokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.Logging
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: JWT
    versions:
    - 7.3.1
    - 8.0.0
    - 8.1.0
    - 8.1.2
    - 8.1.3
    - 8.1.4
    - 8.1.5
    - 8.1.6
  - dependency-name: Twilio
    versions:
    - 5.53.1
    - 5.54.0
    - 5.56.0
    - 5.57.0
    - 5.58.0
  - dependency-name: Portable.BouncyCastle
    versions:
    - 1.8.10
  - dependency-name: Twilio.AspNet.Mvc
    versions:
    - 5.37.2
  - dependency-name: jQuery
    versions:
    - 3.5.1
  - dependency-name: bootstrap
    versions:
    - 3.4.1
  - dependency-name: Microsoft.AspNet.WebPages
    versions:
    - 3.2.7
  - dependency-name: Microsoft.AspNet.Razor
    versions:
    - 3.2.7
  - dependency-name: Microsoft.AspNet.Mvc
    versions:
    - 5.2.7
